-- Phase 2: Core schema aligned to planning.md (users, listings, images, bookmarks, conversations, messages)

-- 1) Enums
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'listing_status') THEN
    CREATE TYPE listing_status AS ENUM ('PENDING', 'ACTIVE', 'SOLD', 'DELETED');
  END IF;
END$$;

-- 2) Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  registration_number TEXT NOT NULL,
  email TEXT NOT NULL,
  phone_number TEXT NULL,
  password_hash TEXT NOT NULL,

  campus TEXT NULL,
  registered_location_text TEXT NULL,
  registered_geo geography(Point, 4326) NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness on email
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users ((lower(email)));
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_registration_number ON users (registration_number);

-- 3) Listings
CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  title TEXT NOT NULL,
  price_ugx BIGINT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  category_code TEXT NOT NULL,
  description TEXT NULL,

  location_text TEXT NULL,
  campus TEXT NULL,
  geo geography(Point, 4326) NULL,

  status listing_status NOT NULL DEFAULT 'PENDING',

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ck_listings_description_len CHECK (description IS NULL OR char_length(description) <= 500),
  CONSTRAINT ck_listings_currency_ugx CHECK (currency = 'UGX'),
  CONSTRAINT ck_listings_price_positive CHECK (price_ugx >= 0)
);

CREATE INDEX IF NOT EXISTS ix_listings_owner_status ON listings (owner_user_id, status);
CREATE INDEX IF NOT EXISTS ix_listings_status_created_at ON listings (status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_listings_geo_gist ON listings USING GIST (geo);

-- 4) Listing images
CREATE TABLE IF NOT EXISTS listing_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,

  public_id TEXT NOT NULL,
  secure_url TEXT NOT NULL,
  width INTEGER NULL,
  height INTEGER NULL,
  bytes BIGINT NULL,
  format TEXT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ux_listing_images_listing_public UNIQUE (listing_id, public_id)
);

CREATE INDEX IF NOT EXISTS ix_listing_images_listing_id ON listing_images (listing_id);

-- 5) Bookmarks
CREATE TABLE IF NOT EXISTS bookmarks (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, listing_id)
);

CREATE INDEX IF NOT EXISTS ix_bookmarks_listing_id ON bookmarks (listing_id);

-- 6) Conversations
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NULL REFERENCES listings(id) ON DELETE SET NULL,
  buyer_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seller_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ck_conversations_buyer_seller_diff CHECK (buyer_user_id <> seller_user_id),
  CONSTRAINT ux_conversations_unique UNIQUE (listing_id, buyer_user_id, seller_user_id)
);

CREATE INDEX IF NOT EXISTS ix_conversations_buyer ON conversations (buyer_user_id);
CREATE INDEX IF NOT EXISTS ix_conversations_seller ON conversations (seller_user_id);

-- 7) Messages
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ck_messages_body_len CHECK (char_length(body) <= 2000)
);

CREATE INDEX IF NOT EXISTS ix_messages_conversation_id_id ON messages (conversation_id, id);
CREATE INDEX IF NOT EXISTS ix_messages_sender_id ON messages (sender_user_id);
